min_version = "2024.9.5"

[env]
PROJECT_NAME = "{{ config_root | basename }}"
NODE_ENV = "development"
DEBUG = "*"

[tools]
node = "24.21.0"
pnpm = "10.34.6"

[tasks.install]
description = "Install Node.js dependencies"
run = "pnpm install --frozen-lockfile"

[tasks.dev]
description = "Run the bot in development mode"
alias = "d"
run = "pnpm dev"

[tasks.serve]
description = "Run the bot in production mode"
alias = "s"
run = "pnpm serve"

[tasks.build]
description = "Build the TypeScript project"
alias = "b"
run = "pnpm build"

[tasks.clean]
description = "Clean build artifacts"
alias = "c"
run = "rm -rf build/dist node_modules"

[tasks.purge]
description = "Purge commands"
alias = "p"
run = "pnpm purge-commands"
